export enum HomeAssistantDomain {
  alarm_control_panel = "alarm_control_panel",
  automation = "automation",
  button = "button",
  binary_sensor = "binary_sensor",
  climate = "climate",
  cover = "cover",
  event = "event",
  fan = "fan",
  humidifier = "humidifier",
  input_boolean = "input_boolean",
  input_button = "input_button",
  light = "light",
  lock = "lock",
  media_player = "media_player",
  remote = "remote",
  scene = "scene",
  script = "script",
  sensor = "sensor",
  switch = "switch",
  vacuum = "vacuum",
  valve = "valve",
  water_heater = "water_heater",
}
